version: '3'

services:
  mongodb:
    image: mongo:4.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=codebasedb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./deployments/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./data/db:/data/db
    networks:
      - web
    ports:
      - 27017:27017
    command: mongod --auth

networks:
  web:
    driver: bridge